script_directory: /scratch/aob2x/DEST_freeze1/snpCalling #Location of the snpCalling scripts (from git repo)
working_directory: /scratch/aob2x/test #Directory where all the data will be processed and where output will be written
poolseq_sync_directory: /scratch/aob2x/DEST_freeze1/snpCalling/test/PoolSeq #Directory holding the masked SYNC files from the main pipeline output
other_sync_directory: /scratch/aob2x/DEST_freeze1/snpCalling/test/dgn #Directory holding the other masked SYNC files, such as DGN data
popSet: all #Population to use: "all" or "PoolSeq"
method: PoolSNP #Method to use for variant calling: "PoolSNP" or "SNAPE"
maf: "001" #Minimum allele frequency (only used with PoolSNP method)
mac: 50 #Minmum allele count (only used with PoolSNP method)
version: test
poolsnp_jobs: 999 #Number of jobs to break the run_poolsnp.sh step into
snpEff_path: ~/snpEff #Where to find the .jar for snpEff and the config file to use
jobs_file: /scratch/aob2x/DEST_freeze1/snpCalling/test/jobs.csv #path to filename, if NA it will run the full genome automatically
